export const images = [
    {
      id: 0,
      src: "/issets/9.png",
      link: "https://full-stack-app-pizzaria.netlify.app/",
      linkGitHub: "https://github.com/alexLDSpedroDEV/Full-Stack-App-Pizzaria",
      type: "full-stack",
      title: "Full-Stack Delivety Pizzaria",
      desc: "Este projeto Full-Stack de delivery web inclui uma landing page atraente e uma interface de menu dinâmica com três opções. Ao selecionar um item, uma lista de produtos aparece e um pop-up exibe os detalhes do pedido. Os itens são facilmente revisados e confirmados no carrinho de compras. Desenvolvido com Next.js, Tailwind e MongoDB, oferece uma experiência moderna e confiável.",
    },
    {
      id: 1,
      src: "/issets/1.png",
      link: "https://loja-de-sushi.netlify.app/",
      type: "full-stack",
      linkGitHub: "https://github.com/alexLDSpedroDEV/Front-End-restaurante-sushi",
      title: "Front-end Sushi",
      desc: " Single Page Application para venda de sushi! Desenvolvida com React, JavaScript, HTML e CSS, esta aplicação oferece uma experiência simples e responsiva para fazer pedidos de sushi online. Experimente agora e aproveite o melhor do sushi com facilidade! 🍣📱",
    },
    {
      id: 2,
      src: "/issets/2.png",
      title: "Front-end Travel",
      type: "front-end",
      link: "https://alexpedro-travel.netlify.app/",
      linkGitHub: "https://github.com/alexLDSpedroDEV/alexLDSpedroDEV.github.io/tree/main/travel",
      desc: "Explore destinos de viagem com facilidade! Meu carrossel, feito com HTML, CSS e JavaScript, apresenta uma seleção de locais deslumbrantes. De praias a montanhas, descubra sua próxima aventura com apenas alguns cliques! 🌍📱",
    },
    {
      id: 3,
      src: "/issets/3.png",
      link: "https://pizzaria-imperial.netlify.app",
      type: "front-end",
      linkGitHub: "https://github.com/alexLDSpedroDEV/land-pag-pizzaria-imperial-react",
      title: "Front-end Pizzaria",
      desc: "Explore nossa seleção de pizzas deliciosas com facilidade! Com React, HTML e CSS, criamos uma experiência de navegação simples e eficaz. Escolha seus sabores favoritos e desfrute do melhor da pizza em apenas alguns cliques! 🍕🖱️",
    },
    {
      id: 4,
      src: "/issets/4.png",
      link: "https://shoppingcat.netlify.app",
      type: "front-end",
      linkGitHub: "https://github.com/alexLDSpedroDEV/Full-Stack-coffe-shop",
      title: "Front-end Shop Coffee",
      desc: "Desperte seus sentidos com nosso café premium! Navegue e encomende facilmente nossos grãos exclusivos. Experimente a praticidade do nosso site responsivo, criado com React.js, HTML, CSS e Bootstrap. Desfrute do melhor café com apenas alguns cliques! ☕🛍️",
    },
    {
      id: 5,
      src: "/issets/5.png",
      link: "https://restaurentegerichti.netlify.app/",
      type: "front-end",
      linkGitHub: "https://github.com/alexLDSpedroDEV/Front-End-gerichet",
      title: "Front-end Restaurante",
      desc: "Desperte seus sentidos com nosso café premium! Navegue e encomende facilmente nossos grãos exclusivos. Experimente a praticidade do nosso site responsivo, criado com React.js, HTML, CSS e Bootstrap. Desfrute do melhor café com apenas alguns cliques! ☕🛍️",
    },
    {
      id: 6,
      src: "/issets/6.png",
      link: "https://bicript.netlify.app",
      type: "front-end",
      linkGitHub: "https://github.com/alexLDSpedroDEV/Bicripto",
      title: "Front-end Bicript",
      desc: "Desperte seus sentidos com nosso café premium! Navegue e encomende facilmente nossos grãos exclusivos. Experimente a praticidade do nosso site responsivo, criado com React.js, HTML, CSS e Bootstrap. Desfrute do melhor café com apenas alguns cliques! ☕🛍️",
    },
    {
      id: 7,
      src: "/issets/7.png",
      link: "https://land-pag-startbucks.netlify.app",
      type: "front-end",
      linkGitHub: "https://github.com/alexLDSpedroDEV/alexLDSpedroDEV.github.io/tree/main/starbusks",
      title: "Front-end Starbicks",
      desc: "Desperte seus sentidos com nosso café premium! Navegue e encomende facilmente nossos grãos exclusivos. Experimente a praticidade do nosso site responsivo, criado com React.js, HTML, CSS e Bootstrap. Desfrute do melhor café com apenas alguns cliques! ☕🛍️",
    },
    {
      id: 8,
      src: "/issets/8.png",
      link: "https://estacao.netlify.app",
      type: "front-end",
      linkGitHub: "https://github.com/alexLDSpedroDEV/alexLDSpedroDEV.github.io/tree/main/esta%C3%A7%C3%B5es",
      title: "Front-end Estações",
      desc: "Desperte seus sentidos com nosso café premium! Navegue e encomende facilmente nossos grãos exclusivos. Experimente a praticidade do nosso site responsivo, criado com React.js, HTML, CSS e Bootstrap. Desfrute do melhor café com apenas alguns cliques! ☕🛍️",
    },
    
  ];