export const images = [
    {
      id: 0,
      src: "/images/banner1.jpeg",
      type: "full-stack",
      title: "Prince of Persia: The Lost Crown",
      link: "https://www.ubisoft.com/pt-br/game/prince-of-persia/the-lost-crown?ucid=SCH-ID_183283&maltcode=digitalmarketing_vidvie_SCH_googlesearch___POPTLC____Action+Adventure+Gamers&addinfo=&gad_source=1&gclid=Cj0KCQjw2PSvBhDjARIsAKc2cgNq9mrib_uy57X5sFYhtzRO2d5YCG5ttFUXMu5YDzVEc4lL5vsyilMaAlKzEALw_wcB",
      desc: "Prince of Persia: The Lost Crown is an action-adventure game developed and published by Ubisoft, part of Prince of Persia series. It was released for Nintendo Switch, PlayStation 4, PlayStation 5, Windows, Xbox One and Xbox Series X/S on 18 January 2024, and received positive reviews from critics.",
    },
    {
      id: 1,
      src: "/images/banner2.jpeg",
      type: "full-stack",
      title: "Palworld",
      link: "https://store.steampowered.com/app/1623730/Palworld/",
      desc: "Palworld is an upcoming action-adventure, survival, and monster-taming game created and published by Japanese developer Pocket Pair. The game is set in an open world populated with animal-like creatures called 'Pals', which players can battle and capture to use for base building, traversal, and combat.",
    },
    {
      id: 2,
      src: "/images/banner3.jpeg",
      type: "full-stack",
      title: "Skull and Bones",
      link: "https://www.ubisoft.com/en-us/game/skull-and-bones",
      desc: "Skull and Bones is a 2024 action-adventure game developed by Ubisoft Singapore and published by Ubisoft. The game revolves around piracy and naval warfare with a fantastical setting in East Africa and Southeast Asia during the late 17th century, the peak of the historical Golden Age of Piracy.",
    },
    {
      id: 3,
      src: "/images/banner4.jpg",
      type: "full-stack",
      title: "Dragon’s Dogma II",
      link: "https://store.steampowered.com/app/2054970/Dragons_Dogma_2/",
      desc: "Dragon's Dogma 2 is a 2024 action role-playing video game developed and published by Capcom. The sequel to Dragon's Dogma, the game was released for PlayStation 5, Windows, and Xbox Series X/S on March 22, 2024. Upon release, it received positive reviews from critics.",
    },
    {
      id: 4,
      src: "/images/banner5.jpg",
      type: "full-stack",
      title: "Call of Duty: Warzone Mobile",
      link: "https://www.callofduty.com/warzonemobile",
      desc: "Call of Duty: Warzone Mobile is a 2024 free-to-play battle royale first-person shooter mobile video game developed and published by Activision. The game was released for iOS and Android on March 21, 2024.",
    },
    {
      id: 5,
      src: "/images/banner6.jpg",
      type: "full-stack",
      title: "Warhammer 40,000: Space Marine 2",
      link: "https://store.steampowered.com/app/2183900/Warhammer_40000_Space_Marine_2/",
      desc: "Warhammer 40,000: Space Marine II is an upcoming third-person shooter hack-n-slash video game developed by Saber Interactive and published by Focus Entertainment. A sequel to Warhammer 40,000: Space Marine, the game is scheduled to release for PlayStation 5, Windows, and Xbox Series X and Series S on 9 September 2024.",
    },
    {
      id: 6,
      src: "/images/banner7.jpg",
      type: "full-stack",
      title: "Black Myth: Wukong",
      link: "https://www.playstation.com/pt-br/games/rise-of-the-ronin/",
      desc: "Black Myth: Wukong is an upcoming action role-playing game by Chinese developer Game Science, based on the classical 16th-century Chinese novel Journey to the West. It is set to release on August 20, 2024",
    },
    {
      id: 7,
      src: "/images/banner8.jpg",
      type: "full-stack",
      title: "Rise of the Rōnin",
      link: "https://www.playstation.com/pt-br/games/rise-of-the-ronin/",
      desc: "Rise of the Rōnin is a 2024 action-role playing video game developed by Koei Tecmo's Team Ninja and published by Sony Interactive Entertainment. The game was released for the PlayStation 5 on March 22, 2024. Upon release, it received generally positive reviews from critics.",
    },
  ];